### ISSUE TITLE
Trailing spaces in ArmA 3 username

### ISSUE THREAD

**Issue by bovine3dom** [michail-nikolaev/task-force-arma-3-radio#1003]
ArmA 3 lets you use trailing spaces in profile names. TeamSpeak does not. This causes TeamSpeak to spam "username already exists" when you join a game server.

Could TFR inform the user of the issue? Would probably save somebody somewhere a headache.

**Comment by dedmen** [comment]
The rename system should be reworked anyway. 
1. Is the renaming really needed?
2. Trim strings so they are allowed by teamspeak
3. Implement own name conflict check to make sure setting the name doesnt error out
4. Handle errors on setting the name.

**Comment by dedmen** [comment]
Im currently solving this but. Im fighting between removing trailing spaces or replacing them with some char. Removing them would create problems if two players had the same ingame name only that one has a trailing space. Replacing them may look ugly.
Also i dont know what char to use when replacing. We have Unicode support so... That may be an interesting task.
For now im implementing it as replacing trailing spaces with a .

**Comment by dedmen** [comment]
Fix is implemented in 1.0. Problem right now is I'm just replacing spaces with . that doesn't look that great though. And we cant just remove the spaces because that could create duplicate names. Can anyone suggest a nice UTF-8 char that I can use as a replacement? If not maybe I'll switch to _ or just remove the chars... Whats the chance anyway that one player is called "test" and another is called "test " but I'd prefer to obivate (just learned a new word) against new issue reports.

**Comment by zgmrvn** [comment]
Alt+255, "unsplitable space" ?

**Comment by dedmen** [comment]
No teamspeak filters that.. We could use http://www.fileformat.info/info/unicode/char/2062/index.htm which is not filtered but.. Teamspeak may fix that

**Comment by dedmen** [comment]
I will replace trailing spaces with _
Currently teamspeak still produces an error on setting the client Nickname. Im not sure what causes that so I will keep this open till i solved that.
