### ISSUE TITLE
Event OnRadioTransmit

### ISSUE THREAD

**Issue by Codingboy** [michail-nikolaev/task-force-arma-3-radio#1038]
I actually try to implement a frequency scan function.
But there is no event to detect if another player is speaking over radio.

https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API%3A-Events

**Comment by rogerxxxx** [comment]
I've been thinking about a scanning feature as well.

Maybe artificially creating a signal spike, if one isn't already created upon keying a radio frequency.  Scanning the frequencies should be extremely easy to implement as we're just talking incrementing the frequency, checking for a spike, and performing freq=freq+1, within an endless loop.

So when the scanning function is checking for a spike, I would surmise a variable named $spike would then need to be assigned an integer each time somebody keys a radio, unless another previously mentioned variable is already created.

I would be extremely interested in such a feature, but fret the developers might already have a hacked method already under the hood.  As in the real world, should be a scan function, or radio scanner.  Another neat idea with this scanner radio, is to have a monitor in the base of the screen printing the frequencies being scanned, and printing a  green frequency number upon a spike.  Option keys such as hold and continue would also need to be, else just pause five seconds and continue scanning regardless of continued spikes on the frequency.

My thoughts are, when I'm in the Area of Operations, a lot of people just choose any frequency sometimes, rather than the default frequencies printed on the map. Most times, there are no default frequencies.

I also think it would be neat to eavesdrop on the enemy once their frequencies are found.  This would significantly help troubleshoot when the enemy are detecting the opposing team!

**Comment by CorruptedHeart** [comment]
I believe you might be looking for `OnTangent` unfortunately it only fires for the local player and not remote players, but you can probably use an event system of some sort to get those events across to remote players if need be.

**Comment by rogerxxxx** [comment]
I'm having a difficult time finding this "OnTangent" program/module.

**Comment by michail-nikolaev** [comment]
@rogerxxxx  check here - https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API%3A-Events
