### ISSUE TITLE
Radio passenger 

### ISSUE THREAD

**Issue by Silente13** [michail-nikolaev/task-force-arma-3-radio#1043]
Hello! I have a question. Can the passenger of only right side of the driver use a long range radio too?

**Comment by michail-nikolaev** [comment]
Currently not possible, but feels like not bad idea...

**Comment by zebra1993** [comment]
could you implement a way to transmit with a vehicle when you are near it. Like taking the mikrotel out through the open door and talk via the vehicle Radio.

**Comment by Scarecrow398** [comment]
Simple way of doing that would just allowing vehicle radio interaction within <5 of the vehicle. 
Not sure how you'd go if you have 5 people trying to use it at once though?

**Comment by zebra1993** [comment]
first come first serv ( Interaction with the Vehicle "Use Vehicle Radio") if a second Person try's to use the Radio, ther will be a message shown "(PLAYER) is using the Radio". 
Just a Idea

**Comment by rogerxxxx** [comment]
Should have no problem to have multiple people using the audio input/output devices all at once.

But then again, we're talking MS Windows, where files are locked from modification by other processes.  As far as I know on Linux, this would absolutely not be a problem.

Probably would have to add a small script before each and every use of the audio input (ie. microphone), to check "if microphone in use, then return and print "Radio in use."  Which would add a slight overhead to the entire script.

**Comment by dedmen** [comment]
@rogerxxxx unrelated

Transmitting with a vehicle while you are near it
1.
Pressing the LR transmit key checks all vehicles in 5m range if you dont have a LR on the back.
If vehicle found use its Radio.
We may not need that for LR configuration as you can only press buttons when youre sitting in the vehicle anyway.

2.
Use ace interaction menu to add  "Use Vehicle Radio" which sets a variable that gets checked on LR transmit.
To disable it again we have to check every <interval> if the player is too far from the vehicle. Because we have to tell the teamspeak plugin that we are not listening anymore.

**Comment by dedmen** [comment]
Modders can now(half a year ago or so) configure any of their vehicles to have a Radio on any slot.
