### ISSUE TITLE
TFAR Needed refactor

### ISSUE THREAD

**Issue by kavinsky** [michail-nikolaev/task-force-arma-3-radio#1111]
Some weeks ago i have a conversation with @michail-nikolaev about the refactor of TFAR, doing some clean up and fix some issues and add new features to the project.

What do you think about this idea?
@michail-nikolaev  @CorruptedHeart @dedmen 

IMHO some parts of the API can be simplified, unify the radio features, and add a pluggable system for 3rd party, remove the Debug Mission and adopt the development environment the ACE Team has created.

Some part of the refactor needed are the split of the addon in separated PBOs by functionality so is easy to maintain.

**Comment by dedmen** [comment]
Yes i was just thinking about refactoring the teamspeak plugins project.
Just the structure of the files in visual studio as they are in no way
ordered. Also split some functions into different files and stuff. I think
its definetly a good idea.
We should also close all the old issues on github that are already solved
or were ignored for months/years.
Yesterday i also noticed all the textures are unavailable as they were
hosted on dropbox i think we could utilize git-lfs and finally do it right.

Am 16.09.2016 14:02 schrieb "Ignacio Muñoz Fernandez" <
notifications@github.com>:

**Comment by kavinsky** [comment]
updated the first comment.

@dedmen yeah reorganizing and refactoring the ts plugin and closing the most critical issues is needed.

i think @michail-nikolaev have the originals so he can sent it to the repo or post it when he has time when you can nkey :)

**Comment by kavinsky** [comment]
@dedmen if you are willing to do the refactor for the plugin, you are most than welcome as a collaborator.

@michail-nikolaev Maybe we should do a organization to manage it.

**Comment by dedmen** [comment]
Before we can think of refactoring we have to process all the open pull
requests to not get conflicts. I was thinking about doing a bit of
refactoring on the teamspeak plugin but even clicking the "format" button
changed almost every line in the file. Where one problem is certainly that
we also dont have a formatting standart ^^.
And i held off doing a PR because Id need to change the project to VS 2015
which not everyone may be using yet and id break some other PRs with that
probably.

**Comment by kavinsky** [comment]
@dedmen you're right, we should merge finished PRs before we start. But some of them are not worth to merge since most probably it will be removed or changed in near future. (i dont mean to delete it, just saving it for later)

**Comment by dedmen** [comment]
Yeah Id certainly take over all the C++ refactoring. Im good in scripting but not really confident enough to touch most of it.
Btw nice ID for this issue :D
What was holding @michail-nikolaev off on version 1.0 ? As i consider TFAR kinda featurecomplete right now. Was it just missing a major cleanup?

**Comment by kavinsky** [comment]
the ID is just perfect!

**Comment by kavinsky** [comment]
@dedmen Addme to Steam: Kavinsky Oss

**Comment by dedmen** [comment]
I added the 0.9.12 milestone which will probably be the last release before 1.0. That is because we need to push changes to master before we do the 1.0 release. Because the new Teamspeak version and CBA settings implementation are very important.
Also... why is there so much stuff in the 0.9.9 milestone although we are already on 0.9.12. I'd recomment not adding stuff to a milestone that is not really planned to be done then. There are issues in there that are inactive for 2 years.

**Comment by kavinsky** [comment]
put your email addresses here ill invite you to slack.

**Comment by dedmen** [comment]
dedmen@dedmen.de
