### ISSUE TITLE
Performance Drop and Stutter With Large Amount of Inventory Items in Backpack

### ISSUE THREAD

**Issue by MSGTJohnson357** [michail-nikolaev/task-force-arma-3-radio#1187]
**Arma 3 Version:** 1.66.139586 stable 
**CBA Version:** 3.1.2.161105
**Task Force Radio Version:** 1.-1.0.168 and 0.9.12

**Mods:**
- @CBA_A3
- @task_force_radio
- @ace3
- @RHSAFRF
- @RHSUSAF
- @RHSGREF
- @SMA V2.7.1
- @TRYK(ver 0.95 fix3) [TRYK's Multi-play Uniforms]
- @VSM - Accessory Pack
- @VSM_Uniforms
- @VSM_VestsHelmets

**Description:**
- A backpack with a large amount of items creates a stutter effect and frame loss (10ish frames) when wearing the backpack. When the backpack is dropped, the stutter and frame loss goes away. As soon as the backpack is picked back up and worn, the performance drops again.

Narrowed the issue to TFAR, does not happen when TFAR is loaded within the game. Unfortunately creates an issue for medics as they need to be able to carry a large amount of medical supplies.

**Steps to reproduce:**
- Put on a backpack with a large amount of items, (300ish in my case)
- Take note of the frame counter and stutter effect
- Drop the backpack and notice the frame counter goes back to normal, + 10ish frames and no more stutter effect.

**Where did the issue occur?**
- Self-Hosted Multiplayer

**RPT log file:**
- http://pastebin.com/cSG2sNMv

**Comment by dedmen** [comment]
This is probably caused by the way we differentiate radios vs normal items.
I have just done a performance improvement in that area yesterday. It
should have a huge impact but performance is probably still bad. That
improvement should be in 1.0 build 169 but I'm gonna continue trying to fix
this issue so not sure if it's gonna be released before this is fixed.

> Are most of the items in your backpack the same type? Could you post your
loadout script on pastebin so I can use it for testing? I have most oft
your mods.
The same also happens in 0.9.12? That narrows the issue down.. Can you also
test if same happens in MP if you are close to another player with a full
backpack like that?
There are two places tfar might scan backpacks. When it scans for all the
frequencies you are listening on and when it scans for nearby radios with
speaker enabled. The one scanning frequencies shouldn't have an impact on
fps. And the one for speakers shouldn't scan the local player which was a
bug i noticed yesterday but I'm not sure if that might cause problems if it
doesn't scan local player.

**Comment by dedmen** [comment]
I've just packed up a bergen backpack with 480 items of ace medical stuff... I think i can notice a framedrop every 5 or so seconds... But nothing more. So it's probably many different items that throw it off

**Comment by dedmen** [comment]
Second bug in TFAR_fnc_radioToRequestCount same cause as it's doing a very similear thing.. Let's take a crack at it.

**Comment by kavinsky** [comment]
Maybe we can change the way the function is called instead of a endless loop call it when you turn on the radio for first time ie.

**Comment by dedmen** [comment]
All perf problems correlating with itemcount in inventory are solved. I'll fix all the other problems i can still find but these are not in the scope of this issue anymore.
You can expect fix in 1.0 build 169
