### ISSUE TITLE
fn_setSwSettings.sqf Semicolon missing

### ISSUE THREAD

**Issue by Syr3L** [michail-nikolaev/task-force-arma-3-radio#1188]
hi dudes!

Was checking how some functions works and i found that in the last if segment there is the semicolon missing which can cause some issues

file is:
\task_force_radio\functions\fn_setSwSettings.sqf 
line 35

keep up the good work mates

**Comment by dedmen** [comment]
Shouldn't cause any issues. A semicolon missing on the end of a script file notates are return value.. Ofc this return value would be bogus because publicVariable returns Nothing. Also the code on master branch is very outdated. master branch is version 0.9.12 and there will be no new 0.9 version. For the next version you have to check out the 1.0 branch like here: fnc_setSwSettings.sqf at michail-nikolaev/task-force-arma-3-radio https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/1.0/addons/core/functions/fnc_setSwSettings.sqf
As you can see it completly changed.
