### ISSUE TITLE
arma 1.68 update x64 not compatible with tfar

### ISSUE THREAD

**Issue by kripto202** [michail-nikolaev/task-force-arma-3-radio#1219]
TFAR is still x32, it isn't compatible with x64 on stable version.

**Comment by coresync2k** [comment]
https://github.com/michail-nikolaev/task-force-arma-3-radio/releases/tag/1.0-PreRelease

**Comment by ElTyranos** [comment]
Do you plan any release soon ? My community hosts public games using A3Sync, swapping DLLs can get boring for most casual players.

**Comment by Morphy2k** [comment]
I have tested the 1.0-dev.217 version. Unfortunately it does not work :-/

Here is my RPT
[Arma3_x64_2017-03-17_00-24-53.rpt.txt](https://github.com/michail-nikolaev/task-force-arma-3-radio/files/849313/Arma3_x64_2017-03-17_00-24-53.rpt.txt)

**Comment by dedmen** [comment]
Using your eyes really helps: https://github.com/michail-nikolaev/task-force-arma-3-radio/releases/tag/0.9.12 pipe_x64.dll has already been available for months.
@Morphy2k your RPT looks fine.
I can't update Steam workshop because Steam doesn't allow collaborators to collaborate.. @michail-nikolaev will do that when he has time.
