### ISSUE TITLE
problem with the TFAR enforce usage module / team leader long range radio

### ISSUE THREAD

**Issue by voodoo23** [michail-nikolaev/task-force-arma-3-radio#1230]
**Arma 3 Version:** `1.68` 
**CBA Version:** `3.2.1` 
**Task Force Radio Version:** `1.0.222`

**Mods:**
- `@CBA_A3`
- `@task_force_radio

**Description:**
- Switching the variable "tf_no_auto_long_range_radio"  to true with the TFAR module or with a script does not seem to work. Soldiers spawn with a Long Range radio. And if you leave the variable to default value (false), soldiers dont spawn with the LR radio.

**Steps to reproduce:**
- Create a simple mission, put some soldiers to play with. Put the TFAR enforce usage module and switch the line "give team leaders a long range radio" to deactivated.

**Where did the issue occur?**
- Dedicated server

**Comment by dedmen** [comment]
`tf_no_auto_long_range_radio` doesn't exit anymore since build 139
Setting CBA settings by setting the variable directly also doesn't work.
`And if you leave the variable to default value (false), soldiers dont spawn with the LR radio.` which is completly correct. Setting `TFAR_giveLongRangeRadioToGroupLeaders` to false doesn't give LR Radios. Which makes sense.
The Module is actually incorrect. If you set it to true the Module script set's the variable to false. I forgot to remove a `!` in there. The Rifleman radios setting in the Module has the same problem.
Fixed in 80b492c59b61226759d11f7252ea09c5771aa551 build 223
