### ISSUE TITLE
Error in TFAR_fnc_getRadioItems (backpackcontainer: Type Array, expected Object)

### ISSUE THREAD

**Issue by cineafx** [michail-nikolaev/task-force-arma-3-radio#1447]
**Arma 3 Version:** `1.88` (stable)
**CBA Version:** `v3.9.0.181012` (stable)
**Task Force Radio Version:** `1.0.302` (Newest on steam workshop)

**Mods:**
```
- @CBA_A3
- @task_force_radio
```
**Description:**
- The command TFAR_fnc_getRadioItems throws: `backpackcontainer: Type Array, expected Object`
- It appears that `backpackContainer _this` has to be `backpackContainer _unit` as `backpackContainer` does not take an array as the parameter.
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/0690b1d086f677a7b1f15125cb2c5b5ab62aede8/addons/core/functions/fnc_getRadioItems.sqf#L28-L30

**Steps to reproduce:**
- Load any scenario with as a unit
- execute `[player] call TFAR_fnc_getRadioItems;`
- observe error

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Multiplayer)

**RPT log file:**
- [Relevant part](https://pastebin.com/RBSmmK6u)
- [Full log](https://pastebin.com/5w5P2D4C)

**Comment by dedmen** [comment]
>The command TFAR_fnc_getRadioItems throws
Only in scheduled. Which is why that bug wasn't detected yet, though I initially wanted handheld radios to not work when in backpack.  So maybe that line should just.. Yes.
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/0690b1d086f677a7b1f15125cb2c5b5ab62aede8/addons/core/functions/fnc_getRadioItems.sqf#L7

So this was "bugged" but still behaved as expected/wanted. Problem is just that it errors in scheduled, though TFAR doesn't ever use that function in scheduled code.
Fix will be just removing that line.
