### ISSUE TITLE
lower headset function

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#880]

**Comment by SageNTitled** [comment]
This is one of the most important features for 1.0 IMO. Many times have I missed important information because I'm listening to so many frequencies and unable to lower volume quickly enough.

I would suggest that it lowers the volume of radios set on speaker as well, so it would be called something else other than "lower headset". Maybe "mute radio" or "muffle radio".

**Comment by dedmen** [comment]
In reality you couldn't influence the volume of speakers that are on nearby players.. Except for telling them to lower their volume.
This will be part of #1144

**Comment by SageNTitled** [comment]
No, not others. I meant your own radios on speaker.

**Comment by dedmen** [comment]
Hotkeys implemented in Pre-release 165.
Still missing a UI indicator. May be incorporated into 1159

**Comment by dedmen** [comment]
Also implemented in ACE Interaction menu.
