### ISSUE TITLE
Vehicle intercom

### ISSUE THREAD

**Issue by kavinsky** [michail-nikolaev/task-force-arma-3-radio#974]
Some vehicles like Helicopters have internal communication device to permit pilots/gunners/crewmans speak between.

https://www.youtube.com/watch?v=P06CXiEMob8

It should no need to use PPT to speak, and have radio effects on the voice.

**Comment by theYoursTruly** [comment]
Any update on this feature?

**Comment by michail-nikolaev** [comment]
Not yet :(

**Comment by Hailstorm12** [comment]
It has been a while since this was mentioned, would be good to see this become a part of the mod, would add a lot to vehicles, and make vehicle crews lives easier.

**Comment by dedmen** [comment]
Theoretically we would just have to add a radio effect to direct speech and ignore the volume on distance calculation, if the other player is in the same vehicle and the vehicle supports intercom. We are already detecting if a player is in a vehicle and add the vehicleIsolation thingy onto players direct speech. So i think it wouldn't be a big problem to add that stuff.

**Comment by CorruptedHeart** [comment]
I don't think it was ever a huge problem to implement, just it will require time to setup the vehicles.

From my side, always a bit too nervous to touch too much in the TS plugin.

**Comment by dedmen** [comment]
Yeah... I understand not wanting to touch the TS plugin XD But my initial refactoring is done. Maybe about one week and then the Plugin is far enough to allow new features. (Besides I'm implementing a new feature right now)

**Comment by kavinsky** [comment]
we can play with the ACE hearing, since intercom its most of times used with protection headsets

**Comment by SlantX** [comment]
Just as a side note, our clan has ACE hearing disabled, since it doesn't really add to the gameplay. Would this work with ACE hearing disabled?

**Comment by dedmen** [comment]
@SlantX sure. We will probably just check if player has a headset with ACE_hearing. Doesn't matter if you enabled the ACE audio effects for that. Not even sure if we want to use that... As we can't have a dependency on ace anyway.

**Comment by kavinsky** [comment]
Maybe he is talking about not using at all the hearing pbo, since ACE its modular he can remove it.

**Comment by dedmen** [comment]
Intercom is kinda implemented. Though its very crappy right now. It's just forced by replacing direct voice with intercom when in vehicle.
It's in Pre-release 139

**Comment by dedmen** [comment]
Intercom fully Implemented now. Can switch between Crew and Cargo channels via ACE Interaction menu. So Tank crew doesn't have to hear Cargo in a troop transporter. By default everyone is in Cargo channel.
The fully implemented system will be in Pre-release 144.
There may be some adjustments to the Intercom volume depending on peoples opinions in Beta testing. Intercom UI with Volume adjust is not planned. Maybe Clientside setting would be good. 
Yeah... #DoThatDedmen

**Comment by BryanBoru** [comment]
are the Crew/Cargo channels dependant on which identified seats you have in the vehicle? Or can everyone get onto Crew from Cargo regardless of seat?
Also, this is tentatively implemented in both ground and air, correct?

**Comment by dedmen** [comment]
Everyone can switch to any channel. By using the imaginary intercom panel behind them.
Yep Its the same system for ground and air. But all Air vehicles have it. And not all ground vehicles do.

**Comment by dedmen** [comment]
Added config Settings to set Intercom volume clientside and disable Intercom serverside.

**Comment by BryanBoru** [comment]
"all Air vehicles have it. And not all ground vehicles do" 
That is preferable, especially compared to other way around. Thanks for reply.

**Comment by Saborknight** [comment]
I know that this version of the intercom has been completed, and you have no idea how excited I am to hear this! 
I was researching before this issue was worked on with the intention of contributing it to TFAR myself. Thank God @dedmen did it, it would have been my first time.
Anyway, the research may still be of some help if you were to further enhance this feature. Please refer to my Google doc: https://docs.google.com/document/d/1zXcXhawZ8-7SCj9aX8UCXeeAzI2khXrMU21d6fYfro4/edit?usp=drivesdk

The research is based off both secondary and primary data (a member in my unit served as a crew chief on a Chinook and continues in a civilian Chinook now).

If you have any questions about the research, I would suggest contacting me at support@saborknight.com .

**Comment by dedmen** [comment]
Thank you for that Information.. But besides being able to use the intercom system externally everything is already done like you wanted i think... Well seperate volume control for the channels is missing because we don't have any UI for the Intercom currently you can only hear people that are on the same channel as you are. And switching channels is only available in the ACE menu for the same reason. And we only have two channels (Crew, Cargo) for now.. could easilly be extended though.

**Comment by kavinsky** [comment]
Great document @Saborknight

**Comment by Saborknight** [comment]
Don't get me wrong, what you have now is excellent! Besides the moving about the vehicle part, you have a more simplified version which would probably work better since it simplifies the need to control the ICS unit. If the players have proper radio discipline then there shouldn't be too much need for any of the other features offered in real life. 
However, maybe there could an implementation in the future of a sort of "Advanced intercom", similar to how ACE separated their medical system.
The only problem I can see with the current intercom implementation is that the player requires ACE to switch channels etc. Unless I am mistaken?

**Comment by kavinsky** [comment]
If you want to contribute a UI for the intercorm that would be great, atm im really fucked up with work and cant do anything, but if you want to start working on the ui i can give you some support on it.

**Comment by Saborknight** [comment]
Alright. So how would that work then? Looking at the code it seems you're mapping interactable areas and then just adding and image in the background, is that right?

**Comment by kavinsky** [comment]
yes, you can use the in-game editor, the best way to start is loading up an existing radio into the editor and then modify. https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/1.0/addons/handhelds/anprc152/ui/anprc152.ext#L1-L17

**Comment by kavinsky** [comment]
Also look for a good frontal image of the ICS, and for real references, for russian and nato equipment if u cant :)

**Comment by dedmen** [comment]
To set the intercom channel you can use this
(vehicle ACE_Player) setVariable [format ['TFAR_IntercomSlot_%1',(netID ACE_Player)],0,true];
the 0 at the end is the channel... you bascially have any number available you need... Don't remember right now how I'm storing it internally.. But atleast 255 channels.
